service: metadata-scraper

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  GetMetadataFromUrl:
    handler: src/handler.getMetadataFromUrl
    description: METADATA SCRAPING FROM A GIVEN WEB PAGE URL
    events:
      - http:
          path: api/getMetadataFromUrl
          method: post
